name: 'Setup git'
description: 'Setup git'
inputs:
  git-email:
    description: 'Git email'
    required: false
  git-username:
    description: 'Git username'
    required: false
runs:
  using: 'composite'
  steps:
    - run: git config --global user.email ${{ inputs.git-email }}
      if: ${{ inputs.git-email }} != null
      shell: sh
    - run: git config --global user.email ${{ inputs.git-username }}
      if: ${{ inputs.git-username }} != null
      shell: sh