name: 'Setup docker'
description: 'Setup docker'
inputs:
  docker-registry:
    description: 'Docker registry domain to authenticate'
    required: false
  docker-username:
    description: 'Docker authentication username'
    required: false
  docker-password:
    description: 'Docker authentication password'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - run: echo ${{ inputs.docker-password }} | docker login ${{ inputs.docker-registry }} -u ${{ inputs.docker-username }} --password-stdin
      if: ${{ inputs.docker-password }} != null && ${{ inputs.docker-registry }} != null && ${{ inputs.docker-username }} != null
      shell: bash