name: 'Cache Node'
description: 'Cache Node'
outputs:
  cache-hit:
    description: 'Is true if cache hit on primary key'
    value: ${{ steps.node-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: node-cache
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
      id: yarn-cache-dir-path
    - uses: actions/cache@v4
      if: steps.yarn-cache-dir-path.outputs.dir != 'undefined'
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-cache-${{ runner.os }}