name: 'Cache Turbo'
description: 'Cache Turbo'
outputs:
  cache-hit:
    description: 'Is true if cache hit on primary key'
    value: ${{ steps.turbo-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - id: get-date
      run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v3
      id: turbo-cache
      with:
        path: node_modules/.cache/turbo
        key: turbo-${{ runner.os }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}-${{ github.job }}-${{ steps.get-date.outputs.date }}-${{ github.ref_name }}